swagger: "2.0"

info:
  title: "Execute Commands API"
  version: "1.0"

basePath: /v2

paths:
  /Broadcast/:
    post:
      operationId: api.commands.Commands.createPlaybook
      responses:
        '200':
          description: 'Fetching smaples'
          schema:
            type: string
            items:
              $ref: '#/definitions/IP' 


definitions:
  IP:
    type: string