swagger: "2.0"

info:
  title: "Discovered Devices API"
  version: "1.0"

basePath: /v1

paths:
  /Devices/{name}:
    get:
      operationId: api.discoveredDevices.Device.discoverDevices
      parameters:
      - name: name
        in: path
        required: true
        type: string
        format: path
      responses:
        '200':
          description: 'Fetch a list of Discovered Devices'
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
  /{path}:
    get:
      operationId: api.startPage.getFile
      parameters:
      - name: path
        in: path
        required: true
        type: string
        format: path
      responses:
        '200':
          description: 'Start page'   
  /IP/:
    get:
      operationId: api.discoveredDevices.Device.getCidrIP
      responses:
        '200':
          description: 'Fetch My IP'
          schema:
            type: string
            items:
              $ref: '#/definitions/IP' 

definitions:
  IP:
    type: string
  Device:
    type: object
    properties:
      id: { type: string }
      MACAddr: { type: string }
      IPAddr: { type: string }